server:
  port: 3001
#  error.include-stacktrace: never

spring:
  application:
    name: auth-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: jmo-service-auth-development
      authentication-database: admin
      username: jmorderadmin
      password: Admin123Admin123
      auto-index-creation: true
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

spring.cloud.gcp:
  project-id: jmorder
  credentials.location: 'file:./service-account.json'

jmo:
  firebase:
    web-api-key: AIzaSyDEt7wa6Y0qjkEXuWriA3DcqjBigPzJR3E
    dynamic-link:
      url-prefix: https://jmorder.page.link
      web-host: https://jmorder.com
      android-package-name: com.rostradamus.jmorder_app
      ios-bundle-id: com.rostradamus.jmorderApp
      ios-app-store-id: 1545071809
      fallback-link: https://jmorder.com/fallback

  kakao:
    clientId: accc52f7a71f2b130554c98f20337d10
  topics:
    data-sync: data-sync
  auth:
    jwt:
      rsa-private-key: |
        -----BEGIN PRIVATE KEY-----
        MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEAmyhujBh2ZXJHjOG7
        yBI21Sx8IYaEJFchusC8P8Q4djnii3jwXu35BFQnNRIy1RiuN4/GBrZlPXvOB0Zd
        JM5gywIDAQABAkB2v5UL59UFg1c7fbBoSXhp4qgGSJtt7LnF4qiw7Q6BfE7P+A9a
        Bvc2c5V6fNHU/xq1awyCqCnkMjmuOmGqcIPBAiEAyRKIigCHGah3oIsFchb63Dle
        f0LzmVc83GbMgFkm8NsCIQDFiv36yfWPai3Hr+2OcJgXE4ck8qwaFCOowF/552Ca
        0QIgKFFMCYfjjxSFsC5QEDllYcUrGo99MvEYJgWC2fWGZmMCIQC+sQ27qnmBl93Z
        hdqsRcSLgi5TXG8GPaqunAYKF3EKAQIhAKh5YZ/i25WBMaJPMOOQP4aBvC7WJOEV
        PtH+DX36uYrn
        -----END PRIVATE KEY-----
      rsa-public-key: |
        -----BEGIN PUBLIC KEY-----
        MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJsobowYdmVyR4zhu8gSNtUsfCGGhCRX
        IbrAvD/EOHY54ot48F7t+QRUJzUSMtUYrjePxga2ZT17zgdGXSTOYMsCAwEAAQ==
        -----END PUBLIC KEY-----
      duration: 900000

logging.level.org.springframework.web.filter:
  CommonsRequestLoggingFilter: DEBUG
